name: adoodlz
description: Adoodlz App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+40

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^2.0.6
  dart_ipify: ^1.0.2
  device_info: ^1.0.0
  dio: ^3.0.10
  extended_image: ^1.1.2
  ffi: ^1.1.2
  firebase_core: ^0.5.2
  firebase_database: ^4.4.0
  firebase_messaging: ^8.0.0-dev.8
  flag: ^3.0.5
  flutter:
    sdk: flutter
  flutter_linkify: ^4.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.19.1
  font_awesome_flutter: ^8.12.0
  forceupdate: ^0.0.6
  google_nav_bar: any
  grouped_buttons: ^1.0.4
  image_picker: ^0.6.7+14
  image_slider: ^1.0.2
  intl: ^0.17.0
  http: ^0.12.1
  intl_phone_field: ^1.4.4
  json_annotation: ^3.1.0
  line_awesome_flutter: ^1.0.1
  linkable: ^1.0.7
  new_version: any
  package_info: ^0.4.3+2
  pin_code_fields: ^6.1.0
  provider: ^4.3.2+2
  shape_of_view: ^1.0.2
  share: ^0.6.5+4
  shared_preferences: ^0.5.10
  sqflite: ^1.3.2+4
  step_progress_indicator: any
  tutorial_coach_mark: ^0.5.1
  url_launcher: ^5.7.10
  validators: ^2.0.1
  webview_flutter: ^1.0.7

dev_dependencies:
  build_runner: ^1.10.3
  change_app_package_name: ^0.1.2
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  lint: ^1.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/send-otp.png
    - assets/images/user_profile.png
    - assets/images/referral.png
    - assets/images/diamond.png
    - assets/images/
    - assets/images/splash.png
    - assets/images/postsOval.png
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800

    - family: Open sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf

    - family: MyCustomIcons2
      fonts:
        - asset: assets/fonts/MyCustomIcons2.ttf
          weight: 800

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 800
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  image: assets/images/logo.png
  color: "ffffff"
